version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: System.IO.Abstractions
    versions:
    - 13.2.10
    - 13.2.11
    - 13.2.15
    - 13.2.17
    - 13.2.20
    - 13.2.23
    - 13.2.24
    - 13.2.25
    - 13.2.28
    - 13.2.9
  - dependency-name: System.IO.Abstractions.TestingHelpers
    versions:
    - 13.2.10
    - 13.2.11
    - 13.2.15
    - 13.2.17
    - 13.2.20
    - 13.2.23
    - 13.2.24
    - 13.2.25
    - 13.2.28
    - 13.2.9
  - dependency-name: MSTest.TestAdapter
    versions:
    - 2.1.2
    - 2.2.1
    - 2.2.2
  - dependency-name: Microsoft.Build.Utilities.Core
    versions:
    - 16.8.0
