trigger:
- master

pool:
  vmImage: windows-2019

stages:
  - template: 'base.yml'
  - stage: Staging
    dependsOn: Build
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    jobs:
    - job: PushToPreview
      steps:
        - checkout: none
        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'current'
            artifactName: 'NuGetPackages'
            itemPattern: '/ci/**'
            targetPath: '$(Pipeline.Workspace)'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'push'
            packagesToPush: '$(Pipeline.Workspace)/*.nupkg'
            nuGetFeedType: 'internal'
            publishVstsFeed: $(Azure.Artifacts.Id)
  # - stage: Production
  #   dependsOn: Staging
  #   condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  #   jobs:
  #     - job: PushToNugetOrg
  #       steps:
  #         - checkout: none
  #         - task: DownloadPipelineArtifact@2
  #           inputs:
  #             buildType: 'current'
  #             artifactName: 'NuGetPackages'
  #             itemPattern: '/master/**'
  #             targetPath: '$(Pipeline.Workspace)'
  #         - task: DotNetCoreCLI@2
  #           inputs:
  #             command: 'push'
  #             packagesToPush: '$(Pipeline.Workspace)/*.nupkg'
  #             nuGetFeedType: 'external'
  #             publishFeedCredentials: 'NuGet.LicenseGatherer'
