trigger:
  branches:
    include:
      - master

pool:
  vmImage: windows-2019

variables:
  BuildConfiguration: Release
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: 'src/license-gatherer.sln'
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: 'src/license-gatherer.sln'
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Pack Master NuGet Packages
  inputs:
    command: 'custom'
    projects: 'src/license-gatherer.sln'
    custom: 'pack'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) --no-build --verbosity Detailed'
- task: DotNetCoreCLI@2
  displayName: Pack CI NuGet Packages
  inputs:
    command: 'custom'
    projects: 'src/license-gatherer.sln'
    custom: 'pack'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) --no-build --version-suffix "ci-$(Build.SourceVersion)-$(Date:yyyyMMdd)" --verbosity Detailed'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.Artifactstagingdirectory)'
    artifact: 'NuGetPackages'
    publishLocation: 'pipeline'