trigger:
  branches:
    include:
      - master

pool:
  vmImage: windows-2019

variables:
  BuildConfiguration: Release

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: 'src/license-gatherer.sln'
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: 'src/license-gatherer.sln'
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Pack NuGet Packages
  inputs:
    command: 'pack'
    packagesToPack: 'src/license-gatherer.sln'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    nobuild: true
    includesymbols: true
    versioningScheme: 'off'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(build.artifactstagingdirectory)'
    artifact: 'generated_packages'
    publishLocation: 'pipeline'
- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: $(Azure.Artifacts.Id)