trigger:
  branches:
    include:
      - master

pool:
  vmImage: windows-2019

variables:
  BuildConfiguration: Release
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: 'src/license-gatherer.sln'
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: 'src/license-gatherer.sln'
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Pack NuGet Packages
  inputs:
    command: 'pack'
    packagesToPack: 'src/license-gatherer.sln'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    nobuild: true
    includesymbols: true
    versioningScheme: 'off'
    buildProperties: '--no-restore'
- task: DotNetCoreCLI@2
  displayName: Pack NuGet Packages
  inputs:
    command: 'pack'
    packagesToPack: 'src/license-gatherer.sln'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    nobuild: true
    includesymbols: true
    versioningScheme: 'off'
    buildProperties: '--version-suffix "-ci.$(Build.SourceVersion)+$(Build.BuildNumber)" --no-restore'
    
- task: DotNetCoreCLI@2
  displayName: Publish NuGet Packages
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: $(Azure.Artifacts.Id)